/*
 * Automatically generated header with JS opcode length constants.
 *
 * Do not edit it, alter jsopcode.tbl instead.
 */
#define JSOP_NOP_LENGTH                  1
#define JSOP_UNDEFINED_LENGTH            1
#define JSOP_POPV_LENGTH                 1
#define JSOP_ENTERWITH_LENGTH            1
#define JSOP_LEAVEWITH_LENGTH            1
#define JSOP_RETURN_LENGTH               1
#define JSOP_GOTO_LENGTH                 5
#define JSOP_IFEQ_LENGTH                 5
#define JSOP_IFNE_LENGTH                 5
#define JSOP_ARGUMENTS_LENGTH            1
#define JSOP_SWAP_LENGTH                 1
#define JSOP_POPN_LENGTH                 3
#define JSOP_DUP_LENGTH                  1
#define JSOP_DUP2_LENGTH                 1
#define JSOP_SETCONST_LENGTH             3
#define JSOP_BITOR_LENGTH                1
#define JSOP_BITXOR_LENGTH               1
#define JSOP_BITAND_LENGTH               1
#define JSOP_EQ_LENGTH                   1
#define JSOP_NE_LENGTH                   1
#define JSOP_LT_LENGTH                   1
#define JSOP_LE_LENGTH                   1
#define JSOP_GT_LENGTH                   1
#define JSOP_GE_LENGTH                   1
#define JSOP_LSH_LENGTH                  1
#define JSOP_RSH_LENGTH                  1
#define JSOP_URSH_LENGTH                 1
#define JSOP_ADD_LENGTH                  1
#define JSOP_SUB_LENGTH                  1
#define JSOP_MUL_LENGTH                  1
#define JSOP_DIV_LENGTH                  1
#define JSOP_MOD_LENGTH                  1
#define JSOP_NOT_LENGTH                  1
#define JSOP_BITNOT_LENGTH               1
#define JSOP_NEG_LENGTH                  1
#define JSOP_POS_LENGTH                  1
#define JSOP_DELNAME_LENGTH              3
#define JSOP_DELPROP_LENGTH              3
#define JSOP_DELELEM_LENGTH              1
#define JSOP_TYPEOF_LENGTH               1
#define JSOP_VOID_LENGTH                 1
#define JSOP_INCNAME_LENGTH              4
#define JSOP_INCPROP_LENGTH              4
#define JSOP_INCELEM_LENGTH              2
#define JSOP_DECNAME_LENGTH              4
#define JSOP_DECPROP_LENGTH              4
#define JSOP_DECELEM_LENGTH              2
#define JSOP_NAMEINC_LENGTH              4
#define JSOP_PROPINC_LENGTH              4
#define JSOP_ELEMINC_LENGTH              2
#define JSOP_NAMEDEC_LENGTH              4
#define JSOP_PROPDEC_LENGTH              4
#define JSOP_ELEMDEC_LENGTH              2
#define JSOP_GETPROP_LENGTH              3
#define JSOP_SETPROP_LENGTH              3
#define JSOP_GETELEM_LENGTH              1
#define JSOP_SETELEM_LENGTH              1
#define JSOP_CALLNAME_LENGTH             3
#define JSOP_CALL_LENGTH                 3
#define JSOP_NAME_LENGTH                 3
#define JSOP_DOUBLE_LENGTH               3
#define JSOP_STRING_LENGTH               3
#define JSOP_ZERO_LENGTH                 1
#define JSOP_ONE_LENGTH                  1
#define JSOP_NULL_LENGTH                 1
#define JSOP_THIS_LENGTH                 1
#define JSOP_FALSE_LENGTH                1
#define JSOP_TRUE_LENGTH                 1
#define JSOP_OR_LENGTH                   5
#define JSOP_AND_LENGTH                  5
#define JSOP_TABLESWITCH_LENGTH         -1
#define JSOP_LOOKUPSWITCH_LENGTH        -1
#define JSOP_STRICTEQ_LENGTH             1
#define JSOP_STRICTNE_LENGTH             1
#define JSOP_SETCALL_LENGTH              1
#define JSOP_ITER_LENGTH                 2
#define JSOP_MOREITER_LENGTH             1
#define JSOP_ITERNEXT_LENGTH             2
#define JSOP_ENDITER_LENGTH              1
#define JSOP_FUNAPPLY_LENGTH             3
#define JSOP_OBJECT_LENGTH               5
#define JSOP_POP_LENGTH                  1
#define JSOP_NEW_LENGTH                  3
#define JSOP_UNUSED0_LENGTH              1
#define JSOP_GETARG_LENGTH               3
#define JSOP_SETARG_LENGTH               3
#define JSOP_GETLOCAL_LENGTH             3
#define JSOP_SETLOCAL_LENGTH             3
#define JSOP_UINT16_LENGTH               3
#define JSOP_NEWINIT_LENGTH              5
#define JSOP_NEWARRAY_LENGTH             4
#define JSOP_NEWOBJECT_LENGTH            5
#define JSOP_ENDINIT_LENGTH              1
#define JSOP_INITPROP_LENGTH             3
#define JSOP_INITELEM_LENGTH             1
#define JSOP_UNUSED14_LENGTH             1
#define JSOP_UNUSED15_LENGTH             1
#define JSOP_INCARG_LENGTH               3
#define JSOP_DECARG_LENGTH               3
#define JSOP_ARGINC_LENGTH               3
#define JSOP_ARGDEC_LENGTH               3
#define JSOP_INCLOCAL_LENGTH             3
#define JSOP_DECLOCAL_LENGTH             3
#define JSOP_LOCALINC_LENGTH             3
#define JSOP_LOCALDEC_LENGTH             3
#define JSOP_LEAVEFORLETIN_LENGTH        1
#define JSOP_LABEL_LENGTH                5
#define JSOP_UNUSED3_LENGTH              1
#define JSOP_FUNCALL_LENGTH              3
#define JSOP_LOOPHEAD_LENGTH             1
#define JSOP_BINDNAME_LENGTH             3
#define JSOP_SETNAME_LENGTH              3
#define JSOP_THROW_LENGTH                1
#define JSOP_IN_LENGTH                   1
#define JSOP_INSTANCEOF_LENGTH           1
#define JSOP_DEBUGGER_LENGTH             1
#define JSOP_GOSUB_LENGTH                5
#define JSOP_RETSUB_LENGTH               1
#define JSOP_EXCEPTION_LENGTH            1
#define JSOP_LINENO_LENGTH               3
#define JSOP_CONDSWITCH_LENGTH           1
#define JSOP_CASE_LENGTH                 5
#define JSOP_DEFAULT_LENGTH              5
#define JSOP_EVAL_LENGTH                 3
#define JSOP_ENUMELEM_LENGTH             1
#define JSOP_GETTER_LENGTH               1
#define JSOP_SETTER_LENGTH               1
#define JSOP_DEFFUN_LENGTH               5
#define JSOP_DEFCONST_LENGTH             3
#define JSOP_DEFVAR_LENGTH               3
#define JSOP_LAMBDA_LENGTH               5
#define JSOP_CALLEE_LENGTH               1
#define JSOP_SETLOCALPOP_LENGTH          3
#define JSOP_PICK_LENGTH                 2
#define JSOP_TRY_LENGTH                  1
#define JSOP_FINALLY_LENGTH              1
#define JSOP_GETFCSLOT_LENGTH            3
#define JSOP_CALLFCSLOT_LENGTH           3
#define JSOP_DEFLOCALFUN_LENGTH          7
#define JSOP_UNUSED4_LENGTH              1
#define JSOP_UNUSED5_LENGTH              1
#define JSOP_UNUSED6_LENGTH              1
#define JSOP_UNUSED7_LENGTH              1
#define JSOP_UNUSED8_LENGTH              1
#define JSOP_UNUSED9_LENGTH              1
#define JSOP_UNUSED10_LENGTH             1
#define JSOP_UNUSED11_LENGTH             1
#define JSOP_UNUSED12_LENGTH             1
#define JSOP_UNUSED13_LENGTH             1
#define JSOP_BACKPATCH_LENGTH            5
#define JSOP_BACKPATCH_POP_LENGTH        5
#define JSOP_THROWING_LENGTH             1
#define JSOP_SETRVAL_LENGTH              1
#define JSOP_RETRVAL_LENGTH              1
#define JSOP_GETGNAME_LENGTH             3
#define JSOP_SETGNAME_LENGTH             3
#define JSOP_INCGNAME_LENGTH             4
#define JSOP_DECGNAME_LENGTH             4
#define JSOP_GNAMEINC_LENGTH             4
#define JSOP_GNAMEDEC_LENGTH             4
#define JSOP_REGEXP_LENGTH               5
#define JSOP_DEFXMLNS_LENGTH             1
#define JSOP_ANYNAME_LENGTH              1
#define JSOP_QNAMEPART_LENGTH            3
#define JSOP_QNAMECONST_LENGTH           3
#define JSOP_QNAME_LENGTH                1
#define JSOP_TOATTRNAME_LENGTH           1
#define JSOP_TOATTRVAL_LENGTH            1
#define JSOP_ADDATTRNAME_LENGTH          1
#define JSOP_ADDATTRVAL_LENGTH           1
#define JSOP_BINDXMLNAME_LENGTH          1
#define JSOP_SETXMLNAME_LENGTH           1
#define JSOP_XMLNAME_LENGTH              1
#define JSOP_DESCENDANTS_LENGTH          1
#define JSOP_FILTER_LENGTH               5
#define JSOP_ENDFILTER_LENGTH            5
#define JSOP_TOXML_LENGTH                1
#define JSOP_TOXMLLIST_LENGTH            1
#define JSOP_XMLTAGEXPR_LENGTH           1
#define JSOP_XMLELTEXPR_LENGTH           1
#define JSOP_XMLCDATA_LENGTH             3
#define JSOP_XMLCOMMENT_LENGTH           3
#define JSOP_XMLPI_LENGTH                3
#define JSOP_DELDESC_LENGTH              1
#define JSOP_CALLPROP_LENGTH             3
#define JSOP_ENTERLET0_LENGTH            5
#define JSOP_ENTERLET1_LENGTH            5
#define JSOP_UINT24_LENGTH               4
#define JSOP_INDEXBASE_LENGTH            2
#define JSOP_RESETBASE_LENGTH            1
#define JSOP_RESETBASE0_LENGTH           1
#define JSOP_STARTXML_LENGTH             1
#define JSOP_STARTXMLEXPR_LENGTH         1
#define JSOP_CALLELEM_LENGTH             1
#define JSOP_STOP_LENGTH                 1
#define JSOP_GETXPROP_LENGTH             3
#define JSOP_CALLXMLNAME_LENGTH          1
#define JSOP_TYPEOFEXPR_LENGTH           1
#define JSOP_ENTERBLOCK_LENGTH           5
#define JSOP_LEAVEBLOCK_LENGTH           3
#define JSOP_UNUSED1_LENGTH              1
#define JSOP_UNUSED2_LENGTH              1
#define JSOP_GENERATOR_LENGTH            1
#define JSOP_YIELD_LENGTH                1
#define JSOP_ARRAYPUSH_LENGTH            3
#define JSOP_GETFUNNS_LENGTH             1
#define JSOP_ENUMCONSTELEM_LENGTH        1
#define JSOP_LEAVEBLOCKEXPR_LENGTH       3
#define JSOP_INDEXBASE1_LENGTH           1
#define JSOP_INDEXBASE2_LENGTH           1
#define JSOP_INDEXBASE3_LENGTH           1
#define JSOP_CALLGNAME_LENGTH            3
#define JSOP_CALLLOCAL_LENGTH            3
#define JSOP_CALLARG_LENGTH              3
#define JSOP_BINDGNAME_LENGTH            3
#define JSOP_INT8_LENGTH                 2
#define JSOP_INT32_LENGTH                5
#define JSOP_LENGTH_LENGTH               3
#define JSOP_HOLE_LENGTH                 1
#define JSOP_UNUSED17_LENGTH             1
#define JSOP_DEFLOCALFUN_FC_LENGTH       7
#define JSOP_LAMBDA_FC_LENGTH            5
#define JSOP_SETMETHOD_LENGTH            3
#define JSOP_INITMETHOD_LENGTH           3
#define JSOP_UNUSED16_LENGTH             1
#define JSOP_TOID_LENGTH                 1
#define JSOP_IMPLICITTHIS_LENGTH         3
#define JSOP_LOOPENTRY_LENGTH            1
